services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - redis
      - mongo

  redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    ports:
      - "6373:6379"
    volumes:
      - redis-data:/data

  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  redis-data:
  mongodb-data: